// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `interfaz.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __interfaz_h__
#define __interfaz_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Demo
{

class interfaz;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::Demo::interfaz>&);
::IceProxy::Ice::Object* upCast(::IceProxy::Demo::interfaz*);

}

}

namespace Demo
{

class interfaz;
bool operator==(const interfaz&, const interfaz&);
bool operator<(const interfaz&, const interfaz&);
::Ice::Object* upCast(::Demo::interfaz*);
typedef ::IceInternal::Handle< ::Demo::interfaz> interfazPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Demo::interfaz> interfazPrx;
void __patch(interfazPtr&, const ::Ice::ObjectPtr&);

}

namespace Demo
{

class Callback_interfaz_checkUsr_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_interfaz_checkUsr_Base> Callback_interfaz_checkUsrPtr;

class Callback_interfaz_altaUsr_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_interfaz_altaUsr_Base> Callback_interfaz_altaUsrPtr;

class Callback_interfaz_bajaUsr_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_interfaz_bajaUsr_Base> Callback_interfaz_bajaUsrPtr;

class Callback_interfaz_actualizarDesc_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_interfaz_actualizarDesc_Base> Callback_interfaz_actualizarDescPtr;

class Callback_interfaz_cambiarTarifa_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_interfaz_cambiarTarifa_Base> Callback_interfaz_cambiarTarifaPtr;

class Callback_interfaz_terminar_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_interfaz_terminar_Base> Callback_interfaz_terminarPtr;

}

namespace IceProxy
{

namespace Demo
{

class interfaz : virtual public ::IceProxy::Ice::Object
{
public:

    void checkUsr(const ::std::string& dni, ::std::string& sout)
    {
        checkUsr(dni, sout, 0);
    }
    void checkUsr(const ::std::string& dni, ::std::string& sout, const ::Ice::Context& __ctx)
    {
        checkUsr(dni, sout, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_checkUsr(const ::std::string& dni, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_checkUsr(dni, 0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_checkUsr(const ::std::string& dni, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_checkUsr(dni, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_checkUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_checkUsr(dni, &__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_checkUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_checkUsr(dni, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_checkUsr(const ::std::string& dni, const ::Ice::Context* __ctx, const ::IceInternal::Function<void (const ::std::string&)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::std::string&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::Demo::interfazPrx __proxy = ::Demo::interfazPrx::uncheckedCast(__result->getProxy());
                ::std::string sout;
                try
                {
                    __proxy->end_checkUsr(sout, __result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(sout);
                }
            }
        
        private:
            
            ::std::function<void (const ::std::string&)> _response;
        };
        return begin_checkUsr(dni, __ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_checkUsr(const ::std::string& dni)
    {
        return begin_checkUsr(dni, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_checkUsr(const ::std::string& dni, const ::Ice::Context& __ctx)
    {
        return begin_checkUsr(dni, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_checkUsr(const ::std::string& dni, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_checkUsr(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_checkUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_checkUsr(dni, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_checkUsr(const ::std::string& dni, const ::Demo::Callback_interfaz_checkUsrPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_checkUsr(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_checkUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::Demo::Callback_interfaz_checkUsrPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_checkUsr(dni, &__ctx, __del, __cookie);
    }

    void end_checkUsr(::std::string& sout, const ::Ice::AsyncResultPtr&);
    
private:

    void checkUsr(const ::std::string&, ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_checkUsr(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento)
    {
        altaUsr(dni, nombre, tarifa, alta, descuento, 0);
    }
    void altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Ice::Context& __ctx)
    {
        altaUsr(dni, nombre, tarifa, alta, descuento, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento)
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Ice::Context& __ctx)
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Demo::Callback_interfaz_altaUsrPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_altaUsr(const ::std::string& dni, const ::std::string& nombre, ::Ice::Byte tarifa, const ::std::string& alta, const ::std::string& descuento, const ::Ice::Context& __ctx, const ::Demo::Callback_interfaz_altaUsrPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_altaUsr(dni, nombre, tarifa, alta, descuento, &__ctx, __del, __cookie);
    }

    void end_altaUsr(const ::Ice::AsyncResultPtr&);
    
private:

    void altaUsr(const ::std::string&, const ::std::string&, ::Ice::Byte, const ::std::string&, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_altaUsr(const ::std::string&, const ::std::string&, ::Ice::Byte, const ::std::string&, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void bajaUsr(const ::std::string& dni)
    {
        bajaUsr(dni, 0);
    }
    void bajaUsr(const ::std::string& dni, const ::Ice::Context& __ctx)
    {
        bajaUsr(dni, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_bajaUsr(const ::std::string& dni, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_bajaUsr(dni, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_bajaUsr(const ::std::string& dni, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_bajaUsr(dni, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_bajaUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_bajaUsr(dni, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_bajaUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_bajaUsr(dni, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_bajaUsr(const ::std::string& dni)
    {
        return begin_bajaUsr(dni, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_bajaUsr(const ::std::string& dni, const ::Ice::Context& __ctx)
    {
        return begin_bajaUsr(dni, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_bajaUsr(const ::std::string& dni, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_bajaUsr(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_bajaUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_bajaUsr(dni, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_bajaUsr(const ::std::string& dni, const ::Demo::Callback_interfaz_bajaUsrPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_bajaUsr(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_bajaUsr(const ::std::string& dni, const ::Ice::Context& __ctx, const ::Demo::Callback_interfaz_bajaUsrPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_bajaUsr(dni, &__ctx, __del, __cookie);
    }

    void end_bajaUsr(const ::Ice::AsyncResultPtr&);
    
private:

    void bajaUsr(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_bajaUsr(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void actualizarDesc(::Ice::Int time)
    {
        actualizarDesc(time, 0);
    }
    void actualizarDesc(::Ice::Int time, const ::Ice::Context& __ctx)
    {
        actualizarDesc(time, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_actualizarDesc(::Ice::Int time, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_actualizarDesc(time, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_actualizarDesc(::Ice::Int time, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_actualizarDesc(time, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_actualizarDesc(::Ice::Int time, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_actualizarDesc(time, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_actualizarDesc(::Ice::Int time, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_actualizarDesc(time, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_actualizarDesc(::Ice::Int time)
    {
        return begin_actualizarDesc(time, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_actualizarDesc(::Ice::Int time, const ::Ice::Context& __ctx)
    {
        return begin_actualizarDesc(time, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_actualizarDesc(::Ice::Int time, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_actualizarDesc(time, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_actualizarDesc(::Ice::Int time, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_actualizarDesc(time, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_actualizarDesc(::Ice::Int time, const ::Demo::Callback_interfaz_actualizarDescPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_actualizarDesc(time, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_actualizarDesc(::Ice::Int time, const ::Ice::Context& __ctx, const ::Demo::Callback_interfaz_actualizarDescPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_actualizarDesc(time, &__ctx, __del, __cookie);
    }

    void end_actualizarDesc(const ::Ice::AsyncResultPtr&);
    
private:

    void actualizarDesc(::Ice::Int, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_actualizarDesc(::Ice::Int, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void cambiarTarifa(const ::std::string& dni)
    {
        cambiarTarifa(dni, 0);
    }
    void cambiarTarifa(const ::std::string& dni, const ::Ice::Context& __ctx)
    {
        cambiarTarifa(dni, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_cambiarTarifa(const ::std::string& dni, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_cambiarTarifa(dni, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_cambiarTarifa(const ::std::string& dni, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_cambiarTarifa(dni, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_cambiarTarifa(const ::std::string& dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_cambiarTarifa(dni, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_cambiarTarifa(const ::std::string& dni, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_cambiarTarifa(dni, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_cambiarTarifa(const ::std::string& dni)
    {
        return begin_cambiarTarifa(dni, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_cambiarTarifa(const ::std::string& dni, const ::Ice::Context& __ctx)
    {
        return begin_cambiarTarifa(dni, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_cambiarTarifa(const ::std::string& dni, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cambiarTarifa(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_cambiarTarifa(const ::std::string& dni, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cambiarTarifa(dni, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_cambiarTarifa(const ::std::string& dni, const ::Demo::Callback_interfaz_cambiarTarifaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cambiarTarifa(dni, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_cambiarTarifa(const ::std::string& dni, const ::Ice::Context& __ctx, const ::Demo::Callback_interfaz_cambiarTarifaPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_cambiarTarifa(dni, &__ctx, __del, __cookie);
    }

    void end_cambiarTarifa(const ::Ice::AsyncResultPtr&);
    
private:

    void cambiarTarifa(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_cambiarTarifa(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void terminar()
    {
        terminar(0);
    }
    void terminar(const ::Ice::Context& __ctx)
    {
        terminar(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_terminar(const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_terminar(0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_terminar(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_terminar(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_terminar(const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_terminar(&__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_terminar(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_terminar(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_terminar()
    {
        return begin_terminar(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_terminar(const ::Ice::Context& __ctx)
    {
        return begin_terminar(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_terminar(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_terminar(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_terminar(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_terminar(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_terminar(const ::Demo::Callback_interfaz_terminarPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_terminar(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_terminar(const ::Ice::Context& __ctx, const ::Demo::Callback_interfaz_terminarPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_terminar(&__ctx, __del, __cookie);
    }

    void end_terminar(const ::Ice::AsyncResultPtr&);
    
private:

    void terminar(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_terminar(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<interfaz> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_secure(bool __secure) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_twoway() const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_oneway() const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_batchOneway() const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_datagram() const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_batchDatagram() const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_compress(bool __compress) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_timeout(int __timeout) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<interfaz> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<interfaz*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Demo
{

class interfaz : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void checkUsr(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void altaUsr(const ::std::string&, const ::std::string&, ::Ice::Byte, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void bajaUsr(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void actualizarDesc(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void cambiarTarifa(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void terminar(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace Demo
{

class interfaz : virtual public ::IceDelegate::Demo::interfaz,
                 virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void checkUsr(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void altaUsr(const ::std::string&, const ::std::string&, ::Ice::Byte, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void bajaUsr(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void actualizarDesc(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void cambiarTarifa(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void terminar(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace Demo
{

class interfaz : virtual public ::IceDelegate::Demo::interfaz,
                 virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void checkUsr(const ::std::string&, ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void altaUsr(const ::std::string&, const ::std::string&, ::Ice::Byte, const ::std::string&, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void bajaUsr(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void actualizarDesc(::Ice::Int, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void cambiarTarifa(const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void terminar(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace Demo
{

class interfaz : virtual public ::Ice::Object
{
public:

    typedef interfazPrx ProxyType;
    typedef interfazPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void checkUsr(const ::std::string&, ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___checkUsr(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void altaUsr(const ::std::string&, const ::std::string&, ::Ice::Byte, const ::std::string&, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___altaUsr(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void bajaUsr(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___bajaUsr(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void actualizarDesc(::Ice::Int, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___actualizarDesc(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void cambiarTarifa(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___cambiarTarifa(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void terminar(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___terminar(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const interfaz& l, const interfaz& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const interfaz& l, const interfaz& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Demo
{

template<class T>
class CallbackNC_interfaz_checkUsr : public Callback_interfaz_checkUsr_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::std::string&);

    CallbackNC_interfaz_checkUsr(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::interfazPrx __proxy = ::Demo::interfazPrx::uncheckedCast(__result->getProxy());
        ::std::string sout;
        try
        {
            __proxy->end_checkUsr(sout, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(sout);
        }
    }

    Response response;
};

template<class T> Callback_interfaz_checkUsrPtr
newCallback_interfaz_checkUsr(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_checkUsr<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_checkUsrPtr
newCallback_interfaz_checkUsr(T* instance, void (T::*cb)(const ::std::string&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_checkUsr<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_interfaz_checkUsr : public Callback_interfaz_checkUsr_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::std::string&, const CT&);

    Callback_interfaz_checkUsr(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Demo::interfazPrx __proxy = ::Demo::interfazPrx::uncheckedCast(__result->getProxy());
        ::std::string sout;
        try
        {
            __proxy->end_checkUsr(sout, __result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(sout, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_interfaz_checkUsrPtr
newCallback_interfaz_checkUsr(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_checkUsr<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_checkUsrPtr
newCallback_interfaz_checkUsr(T* instance, void (T::*cb)(const ::std::string&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_checkUsr<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_interfaz_altaUsr : public Callback_interfaz_altaUsr_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_interfaz_altaUsr(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_altaUsr<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_altaUsr<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_altaUsr<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_altaUsr<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_interfaz_altaUsr : public Callback_interfaz_altaUsr_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_interfaz_altaUsr(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_altaUsr<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_altaUsr<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_altaUsr<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_altaUsrPtr
newCallback_interfaz_altaUsr(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_altaUsr<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_interfaz_bajaUsr : public Callback_interfaz_bajaUsr_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_interfaz_bajaUsr(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_bajaUsr<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_bajaUsr<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_bajaUsr<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_bajaUsr<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_interfaz_bajaUsr : public Callback_interfaz_bajaUsr_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_interfaz_bajaUsr(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_bajaUsr<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_bajaUsr<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_bajaUsr<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_bajaUsrPtr
newCallback_interfaz_bajaUsr(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_bajaUsr<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_interfaz_actualizarDesc : public Callback_interfaz_actualizarDesc_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_interfaz_actualizarDesc(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_actualizarDesc<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_actualizarDesc<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_actualizarDesc<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_actualizarDesc<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_interfaz_actualizarDesc : public Callback_interfaz_actualizarDesc_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_interfaz_actualizarDesc(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_actualizarDesc<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_actualizarDesc<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_actualizarDesc<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_actualizarDescPtr
newCallback_interfaz_actualizarDesc(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_actualizarDesc<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_interfaz_cambiarTarifa : public Callback_interfaz_cambiarTarifa_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_interfaz_cambiarTarifa(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_cambiarTarifa<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_cambiarTarifa<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_cambiarTarifa<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_cambiarTarifa<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_interfaz_cambiarTarifa : public Callback_interfaz_cambiarTarifa_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_interfaz_cambiarTarifa(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_cambiarTarifa<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_cambiarTarifa<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_cambiarTarifa<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_cambiarTarifaPtr
newCallback_interfaz_cambiarTarifa(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_cambiarTarifa<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_interfaz_terminar : public Callback_interfaz_terminar_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_interfaz_terminar(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_terminar<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_terminar<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_terminar<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_interfaz_terminar<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_interfaz_terminar : public Callback_interfaz_terminar_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_interfaz_terminar(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_terminar<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_terminar<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_terminar<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_interfaz_terminarPtr
newCallback_interfaz_terminar(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_interfaz_terminar<T, CT>(instance, 0, excb, sentcb);
}

}

#endif
