// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `StringService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <StringService.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_UC3M_StringService_ids[2] =
{
    "::Ice::Object",
    "::UC3M::StringService"
};
const ::std::string iceC_UC3M_StringService_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "stringSize",
    "toUpperCase"
};
const ::std::string iceC_UC3M_StringService_stringSize_name = "stringSize";
const ::std::string iceC_UC3M_StringService_toUpperCase_name = "toUpperCase";

}

bool
UC3M::StringService::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_UC3M_StringService_ids, iceC_UC3M_StringService_ids + 2, s);
}

::std::vector<::std::string>
UC3M::StringService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_UC3M_StringService_ids[0], &iceC_UC3M_StringService_ids[2]);
}

::std::string
UC3M::StringService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
UC3M::StringService::ice_staticId()
{
    static const ::std::string typeId = "::UC3M::StringService";
    return typeId;
}

bool
UC3M::StringService::_iceD_stringSize(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->readAll(iceP_s);
    inS.endReadParams();
    int ret = this->stringSize(::std::move(iceP_s), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
UC3M::StringService::_iceD_toUpperCase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->readAll(iceP_s);
    inS.endReadParams();
    ::std::string ret = this->toUpperCase(::std::move(iceP_s), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
UC3M::StringService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_UC3M_StringService_ops, iceC_UC3M_StringService_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_UC3M_StringService_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_stringSize(in, current);
        }
        case 5:
        {
            return _iceD_toUpperCase(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
UC3M::StringServicePrx::_iceI_stringSize(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>& outAsync, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UC3M_StringService_stringSize_name);
    outAsync->invoke(iceC_UC3M_StringService_stringSize_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_s);
        },
        nullptr);
}

void
UC3M::StringServicePrx::_iceI_toUpperCase(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>& outAsync, const ::std::string& iceP_s, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_UC3M_StringService_toUpperCase_name);
    outAsync->invoke(iceC_UC3M_StringService_toUpperCase_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_s);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
UC3M::StringServicePrx::_newInstance() const
{
    return ::IceInternal::createProxy<StringServicePrx>();
}

const ::std::string&
UC3M::StringServicePrx::ice_staticId()
{
    return UC3M::StringService::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_UC3M_StringService_stringSize_name = "stringSize";

const ::std::string iceC_UC3M_StringService_toUpperCase_name = "toUpperCase";

}
::IceProxy::Ice::Object* ::IceProxy::UC3M::upCast(::IceProxy::UC3M::StringService* p) { return p; }

void
::IceProxy::UC3M::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::UC3M::StringService>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::UC3M::StringService;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::UC3M::StringService::_iceI_begin_stringSize(const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UC3M_StringService_stringSize_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UC3M_StringService_stringSize_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UC3M_StringService_stringSize_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_UC3M_StringService_stringSize_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Ice::Int
IceProxy::UC3M::StringService::end_stringSize(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UC3M_StringService_stringSize_name);
    ::Ice::Int ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::UC3M::StringService::_iceI_begin_toUpperCase(const ::std::string& iceP_s, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_UC3M_StringService_toUpperCase_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_UC3M_StringService_toUpperCase_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_UC3M_StringService_toUpperCase_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_s);
        result->endWriteParams();
        result->invoke(iceC_UC3M_StringService_toUpperCase_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::std::string
IceProxy::UC3M::StringService::end_toUpperCase(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_UC3M_StringService_toUpperCase_name);
    ::std::string ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::IceProxy::Ice::Object*
IceProxy::UC3M::StringService::_newInstance() const
{
    return new StringService;
}

const ::std::string&
IceProxy::UC3M::StringService::ice_staticId()
{
    return ::UC3M::StringService::ice_staticId();
}

UC3M::StringService::~StringService()
{
}

::Ice::Object* UC3M::upCast(::UC3M::StringService* p) { return p; }


namespace
{
const ::std::string iceC_UC3M_StringService_ids[2] =
{
    "::Ice::Object",
    "::UC3M::StringService"
};

}

bool
UC3M::StringService::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_UC3M_StringService_ids, iceC_UC3M_StringService_ids + 2, s);
}

::std::vector< ::std::string>
UC3M::StringService::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_UC3M_StringService_ids[0], &iceC_UC3M_StringService_ids[2]);
}

const ::std::string&
UC3M::StringService::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
UC3M::StringService::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::UC3M::StringService";
    return typeId;
#else
    return iceC_UC3M_StringService_ids[1];
#endif
}

bool
UC3M::StringService::_iceD_stringSize(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->read(iceP_s);
    inS.endReadParams();
    ::Ice::Int ret = this->stringSize(iceP_s, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

bool
UC3M::StringService::_iceD_toUpperCase(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_s;
    istr->read(iceP_s);
    inS.endReadParams();
    ::std::string ret = this->toUpperCase(iceP_s, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

namespace
{
const ::std::string iceC_UC3M_StringService_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "stringSize",
    "toUpperCase"
};

}

bool
UC3M::StringService::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_UC3M_StringService_all, iceC_UC3M_StringService_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_UC3M_StringService_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_stringSize(in, current);
        }
        case 5:
        {
            return _iceD_toUpperCase(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
UC3M::StringService::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::UC3M::StringService, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
UC3M::StringService::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::UC3M::StringService, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
UC3M::_icePatchObjectPtr(StringServicePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::UC3M::StringServicePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::UC3M::StringService::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
